# RANDOM WALLETS MODE
RANDOM_WALLET = True  # True/False

SLEEP_FROM = 500  # Second
SLEEP_TO = 4000  # Second

QUANTITY_THREADS = 1

THREAD_SLEEP_FROM = 15
THREAD_SLEEP_TO = 120

# GWEI CONTROL MODE
CHECK_GWEI = True  # True/False
MAX_GWEI = 15

MAX_PRIORITY_FEE = {
    "ethereum": 0.01,
    "polygon": 40,
    "arbitrum": 0.1,
    "base": 0.1,
    "zksync": 0.25,
}

GAS_MULTIPLIER = 1.3

# RETRY MODE
RETRY_COUNT = 3

LAYERSWAP_API_KEY = ""

SCROLL_FEE_INACCURACY = 0.00001

MIN_ALL_AMOUNT_ETH_PERCENT = 90
MAX_ALL_AMOUNT_ETH_PERCENT = 95